server { listen 80; return 301 https://$host:8443$request_uri; }
server {
  listen 8443 ssl;
  ssl_certificate /etc/nginx/certs/ito.crt; ssl_certificate_key /etc/nginx/certs/ito.key;
  root /usr/share/nginx/html; index index.html;
  location /driver/ { proxy_pass http://127.0.0.1:8001/; }
  location /processor/ { proxy_pass http://127.0.0.1:8002/; }
  location / { try_files $uri /index.html; }
}
